CREATE DATABASE chirpy;

USE chirpy;

CREATE TABLE `chirps` (
  -- TABLE CODE TO GO HERE id, author, chirp, and time created.
  id int NOT NULL AUTO_INCREMENT,
  author varchar(255) NOT NULL,
  chirp varchar(255) NOT NULL,
  ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  dt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);